[
functions
]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  directory = "functions"

[[
redirects
]]
  force = true
  from = "/app/*"
  status = 200
  to = "/.netlify/functions/app/:splat"